# Generated by Django 3.2.4 on 2021-06-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='star',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
